format = """
[](#1E1E2E)\
$python\
$username\
[](bg:#313244 fg:#1E1E2E)\
$directory\
[](fg:#313244 bg:#45475A)\
$git_branch\
$git_status\
[](fg:#45475A bg:#A6ADC8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#A6ADC8 bg:#81A1C1)\
$docker_context\
[](fg:#81A1C1 bg:#6887B7)\
$time\
[ ](fg:#6887B7)\
"""

command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
# [username]
# show_always = true
# style_user = "bg:#1E1E2E"
# style_root = "bg:#1E1E2E"
# format = '[$user ]($style)'

[directory]
style = "bg:#313244"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#A6ADC8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#81A1C1"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#A6ADC8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#A6ADC8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
# symbol = ""
style = "bg:#45475A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#45475A"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#A6ADC8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#A6ADC8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#A6ADC8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#A6ADC8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#A6ADC8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#A6ADC8"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#1E1E2E"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#A6ADC8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6887B7"
format = '[ $time ]($style)'
