[colors.bright]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#cba6f7"
red = "#f38ba8"
white = "#bac2de"
yellow = "#f9e2af"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#45475a"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#cba6f7"
red = "#f38ba8"
white = "#bac2de"
yellow = "#f9e2af"

[colors.primary]
background = "#1e1e2e"  # "#1e1e2e" closely matches the Mocha base background color
foreground = "#cdd6f4"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.normal]
family = "JetBrainsMono"
style = "Bold"

[scrolling]
history = 100

[window]
opacity = 0.90

[window.padding]
x = 15
y = 15
